AWSTemplateFormatVersion: '2010-09-09'
Resources:
  DocumentConversionBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: document-conversion-bucket

  DocumentConversionFunction:
    Type: AWS::Lambda::Function
    Properties:
      Handler: src/lambda_function.lambda_handler
      Runtime: python3.8
      Role: arn:aws:iam::your-account-id:role/lambda-execution-role
      Code:
        S3Bucket: your-code-bucket
        S3Key: lambda_function.zip
